### ISSUE TITLE
Discussion - resync after action feature

### ISSUE THREAD

**Issue by TobiasOetzel** [js-soft/wdi5#101]
Hello,

When i am using wdi5 to trigger an action like:
`browser.asControl(inputSelector).enterText('new Text');`
It is possible that webrequests etc are triggered when the action is fired.

We have a setup where the webapplication is hitting a mockserver that runs in the same context as the tests.
So we can write something like
`assert(requests.done()).toBe(true)`
If that is done, the test might fail, since the command that is entering the text does not wait until new async processes introduced by the action are done.

If you like wdi5 could sync again after an action, using an empty Opa5 waitFor with automatic waiting to true.

This way you can also track performance better. Since the time spend actually shows on the action that enters the text and not on the next action that is taking over the sync from the previous one.

Let me know if you think it is a good way to provide this as a pull request.

**Comment by vobu** [comment]
hi, very well spotted! sure thing it would be awesome if you could bolt in a `waitFor` to align `wdi5`‘s `enterText` with the ui5 event lifecycle!

**Comment by vobu** [comment]
given that the `async` rewrite is done with v0.8.x, you're a go @TobiasOetzel :)
