### ISSUE TITLE
How to set the waitFor timeout ?

### ISSUE THREAD

**Issue by ArnaudBuchholz** [js-soft/wdi5#102]
Hello, I am playing a bit with the tool to migrate some UIVeri5 scripts I own and I am facing an issue with a timeout that seems to be set to 15s (the default of OPA ?).
Can we increase the timeout globally or for a given browser.asControl call ?

**Comment by vobu** [comment]
Hi, currently there's no option to configure `waitFor` timeouts (yet) - we've put in some defaults for "flaky" UI5 versions (https://github.com/js-soft/wdi5/blob/7e008471e6ddf9ec228febba3c4260bda7eb3773/wdio-ui5-service/src/lib/wdioUi5-index.js#L48), but that's about it...mind to PR this 😸 ?

**Comment by ArnaudBuchholz** [comment]
@vobu Since I am new to the project (and WebDriver.io) what would be the best approach to set this timeout.
I see several ways :
- Inside the ` browser.asControl` itself (maybe at the same level than the selector)
- Inside the wdi.conf (is there a section you can grab parameters from) ?

**Comment by vobu** [comment]
i'll get back to you (also with regard to #103 ), currently short on time → please be patient until the beginning of next week 🙏

**Comment by vobu** [comment]
closed via #103 - 🙌  thanks for your contribution, @ArnaudBuchholz! Honored to have you amongst the contributors :)
