### ISSUE TITLE
[Question] Is it possible to assert a UI5 control is invisible

### ISSUE THREAD

**Issue by cwang1221** [js-soft/wdi5#105]
Hi Experts,

I'm new to WDI5, I was trying to assert a UI5 control is not visible on UI, but it didn't work.
```
var input= browser.asControl({
            selector: {
                id: "myInput",
                viewName: "myView",
                visible: false
            }
        });

        expect(input.getVisible()).toBe(false);
```

It seems that I can only assert visible controls, but not invisible ones?

Thank you and best regards.

**Comment by vobu** [comment]
interesting observation. AFAIK, we don't have a testcase for you invisible elements yet.
is your `input` actually in the DOM, hidden by css? or not rendered yet? can you provide more code-context as to what control etc pp
please?

**Comment by cwang1221** [comment]
Thank you @vobu !
We just used the standard UI5 function `myInput.setVisible(false)` to hide it. This means:

1. UI5 adds a hidden DOM element for this control:
![image](https://user-images.githubusercontent.com/7602106/147622865-e1b137f4-6e6c-4d91-8536-ac7ea4673864.png)
2. But the DOM element is not an input. UI5 does not just add an input DOM and hide it. A visible input DOM should look like:
![image](https://user-images.githubusercontent.com/7602106/147622999-0e33f34c-fc1b-4687-b078-382ee4c878df.png)

Since WDI5's selector is very similar to OPA5's, I also tried `visible: false`, which means "I want to locate the control no matter if it's visible or not" in OPA5. But it didn't work.
![image](https://user-images.githubusercontent.com/7602106/147623229-14ecafa6-21d8-44e4-bafe-2f92bc768bf1.png)

The test scenario is, I want to assert the input is successfully hidden with `myInput.setVisible(false)`. I know this should be done with OPA5 test. But I just want to see if WDI5 can achieve it.

Thank you!

**Comment by vobu** [comment]
thanks for providing the details!
I got curious and validated your use case 
→ result: doesn't work, meaning `wdi5` currently doesn't support the `visible: false` property of `sap.ui.test.Opa5#waitFor` 😒 

But I've added this as a feature request 😸: #106 

FWIW, you can still locate the DOM equivalent of the (unrendered) UI5 control by utilizing `wdio`'s native feature (that `wdi5` is built on):
UI5 control:
```xml
<!-- sap.m namespace -->
<Input id="visibleInputField"
value="bla"
visible="false" />
```

```js
const id = 'visibleInputField';
// wdio-native selector
const wdioInput = browser.$(`[id$="${id}"]`); // ID ends with "visibleInputField"
expect(wdioInput.getProperty('id')).toContain('sap-ui-invisible');
```

**Comment by cwang1221** [comment]
Thank you @vobu ! It's really great to see improvements in wdi5!
