### ISSUE TITLE
feature request: support `visible: false` of sap.ui.test.Opa5#waitFor to locate UI5 controls

### ISSUE THREAD

**Issue by vobu** [js-soft/wdi5#106]
see documentation at https://ui5.sap.com/#/api/sap.ui.test.Opa5%23methods/waitFor

**Comment by vobu** [comment]
not stale, but will be tried

**Comment by maximnaidenov** [comment]
Visible, interactable, ...everything that waitFor accepts is supported in the declarative control locators that RecordReply handles. So just avoid parsing the selector:{} and all those features will work out of the box.

**Comment by vobu** [comment]
still on the roadmap, will be done

**Comment by vobu** [comment]
something the OPA runtime should deliver for us, but prove is pending
also potentially something for @hmanchev and colleagues
