### ISSUE TITLE
Failed to get count of items in a sap.m.Table

### ISSUE THREAD

**Issue by cwang1221** [js-soft/wdi5#109]
Hi Experts,

In my test, I tried to assert the count of items in a sap.m.Table.

Firstly I tried it like this:
```
const table = browser.asControl({
    selector: {
        id: "idDetailTable",
        viewName: "deleteDataSubjects.view.Detail"
    }
});
const items = table.getItems();
expect(items.length).toBe(1);
```
But I got the following error:
![image](https://user-images.githubusercontent.com/7602106/149251694-5f710a25-5fbe-432e-8584-74f3ef70f706.png)

When I debug it, I could see that I successfully got the table object:
![image](https://user-images.githubusercontent.com/7602106/149252169-fa29d1e1-273f-4226-a7a3-639ecbd99aa2.png)

But it didn't generate the "getItems" method:
![image](https://user-images.githubusercontent.com/7602106/149252231-61a45c1f-4505-4ded-a071-3f8c6e06568b.png)

Then I tried this:
```
const table = browser.asControl({
    selector: {
        id: "idDetailTable",
        viewName: "deleteDataSubjects.view.Detail"
    }
});
const items = table.getAggregation("items");
expect(items.length).toBe(1);
```

I could successfully get the items as `[]` and the assertion failed:
![image](https://user-images.githubusercontent.com/7602106/149252403-0f250b2e-0fb3-4e47-95f8-0ef4424463d3.png)

I got the selector of the table from the test recorder:
![image](https://user-images.githubusercontent.com/7602106/149252503-110e2d69-d619-4ea7-95c6-cb70d311ec9d.png)

Some other hint: the data resource of the table is OData, e.g. one cell of it is like:
```
{
        controlType: "sap.m.ObjectStatus",
        viewName: "deleteDataSubjects.view.Detail",
        bindingPath: {
            path: "/ResidenceExpiredDataSubjects(jobID='9223372036854775807',dataSubjectGuid='1641982475494')",
            propertyPath: "dataSubjectID",
            modelName: "mainODataModel"
        }
    }
```

Thank you and best regards,
Cong

**Comment by dominikfeininger** [comment]
Hi, can you please try `interaction: „root“`. Might be already the solution.

see: https://github.com/js-soft/wdi5/issues/61

**Comment by vobu** [comment]
code-wise example: https://github.com/js-soft/wdi5/blob/9ad347d07eb99e23678cc83def7c3006be77e8ff/wdio-ui5-service/test/ui5.test.js#L9

**Comment by cwang1221** [comment]
@dominikfeininger Thank you! It really works. Maybe it's better to document it in the readme or somewhere.
