### ISSUE TITLE
call of _getControl() failed  for UI5 element DatePicker 

### ISSUE THREAD

**Issue by nair-sumesh** [js-soft/wdi5#116]
Hi,

I tried to migrate the UIVERI5 recording for sap.m.DatePicker UI5 element, and it seems that WDI5 is unable to handle it.

The error thrown is as follows:
```
[0-0] ERROR: call of _getControl() failed because of: Error: No DOM element found using the control selector {"id":"application-xxxxxxxxxx-component---xxxxxxx--startDateTimePicker-cal--Month0-20220113"}
[0-0] applicationxxxxxxxxxxcomponentxxxxxxxxxstartdatetimepickercalmonth020220113 has no sReplFunctionNames
[0-0] creating internal control with id applicationxxxxxxxxxxcomponentxxxxxxxxxstartdatetimepickercalmonth020220113 
[0-0] ERROR: call of _getControl() failed because of: Error: No DOM element found using the control selector {"id":"application-xxxxxxxxxx-component---xxxxxxx--startDateTimePicker-cal--Month0-20220113"}
```

The code
```
browser.asControl({
			selector: {
				id: "application-xxxxxxxxxx-component---xxxxxxx--startDateTimePicker-cal--Month0-20220113"
			},
			forceSelect: true
		}).getWebElement().click(); 
```

In the above code (after I have clicked on the **DatePicker-icon**-> I see a date picker popup), I select a date in the past. 

Similarly the  code for selection of month also fails.
```
 browser.asControl({
			selector: {
				id: "application-xxxxxxxxxx-component---xxxxxxx--startDateTimePicker-cal--MP-m0"
			},
			forceSelect: true
		}).getWebElement().click();
```
Initially  I thought, it was a caching issue, and therefore used **forceSelect : true**.
However this did not work.

Thanks,
SN

**Comment by vobu** [comment]
hi, two things I'd recommend:
- use `await browser.screenshot("datepicker")` before the `browser.asControl` to take a screenshot and see what the pop-up looks like. probably there's a clue as to why the `selector` fails
- take a look at https://github.com/ui5-community/ui5-ecosystem-showcase/blob/3e085f09a50aec73c7f10614994c65d9f43804cd/packages/ui5-app/webapp/test/e2e-wdi5/tests.test.js#L61 where there's also a datepicker operated via `wdi5`

**Comment by dominikfeininger** [comment]
The calendar- date buttons in the UI5 Datepicker are not UI5 controls by itself. 

eg. 
`sap.ui.getCore().byId("container-Sample---Main--idDateTime-cal--Month0-20220112")` will return `undefined`

this means you need to use wdio's build in functionality to `$` to retrieve these elements.

**Comment by dominikfeininger** [comment]
see https://github.com/js-soft/wdi5/pull/117
