### ISSUE TITLE
Working with ancestor in selector

### ISSUE THREAD

**Issue by netnic0** [js-soft/wdi5#120]
Hi,
We would like to migrate from another tool.
We have a lot of element selector using the ancestor due to a complex tree of elements.
Is will be possible to have such as propertie now or in the futur? Or if not, how we can write our wdio scripts to easely find our element by their parents (potentially nested)
Thanks a lot,
ND

**Comment by vobu** [comment]
there is no `ancestor` selector in `wdi5` yet.  but it's on the roadmap (not yet public, but hopefully asap).
So the legal thingies pan out in Jan, I can already say that we'll have all [UIveri5/OPA5 matchers](https://ui5.sap.com/#/api/sap.ui.test.matchers) in `wdi5` by March.

**Comment by netnic0** [comment]
Thanks a lot!

Le ven. 21 janv. 2022 à 20:45, Volker Buzek ***@***.***> a
écrit :
