### ISSUE TITLE
Cannot use ui5 methods on ComboBox

### ISSUE THREAD

**Issue by astarovojtov** [js-soft/wdi5#121]
Hello

I cannot get `ComboBox` control to use UI5 methods like `getItems()`. Trying to call it throws `getItems is not a function`.
Seems like `browser.asControl` returns a reference to the `ComboBox` arrow. Tried to use id of the control but it always returns the arrow itself that simply doesn't have the method. 

Somehow same I stumble upon same errors trying to access ` sap.m.Table.getMode()` or even `.getId()`. At the same time `sap.m.Input.setValue()` or `sap.m.CheckBox.setSelected()` works just fine. Was following the example provided in **fluent async api** section.

Am I doing it wrong?

Fragment of my code 
```
await browser.asControl({
    interaction: 'root',
    selector: {
        controlType: 'sap.m.ComboBox',
        id: /.*boardArea$/
    }
}).getItems()
```

**Comment by vobu** [comment]
`interaction: 'root'` needs to go into the `selector`:

```js
await browser.asControl({
    selector: {
        interaction: 'root',
        controlType: 'sap.m.ComboBox',
        id: /.*boardArea$/
    }
}).getItems()
```

**Comment by astarovojtov** [comment]
Thank you. My bad. 

Though it didn't fix the issue completely. 
`await browser.asControl().getItems`
 throws `.getItems is not a function`

```
const boardArea = await browser.asControl();
await boardArea.getItems() 
```
works but returns `undefined` though there are items for sure
tried to call `getId()` - also returns `undefined`

**Comment by vobu** [comment]
i played around a little with retrieving a `sap.m.ComboBox` and indeed, there's something wrong in the neighborhood™ 👻 
I'll flag this issue and we'll investigate

**Comment by vobu** [comment]
on the [roadmap](https://github.com/orgs/js-soft/projects/1)

**Comment by ph-alsvik** [comment]
Hi guys!

I’ve tried to get the items in the aggregation for the combobox, also. A simple test script like this:

```javascript
describe("combobox test", () => {
    it("get combobox control items", async () => {
        oSelector = {
            forceSelect: true,
            selector: {
                interaction: "root",
                id: "combobox",
                viewName: "sap.m.sample.ComboBox.view.ComboBox"
            }
        }
        const combobox = await browser.asControl(oSelector);
        const items = await combobox.getItems();
    });
});
```

While running [this sample app](https://sapui5.hana.ondemand.com/#/entity/sap.m.ComboBox/sample/sap.m.sample.ComboBox) from the UI5 SDK.

I get the following error in the test log:
```
[0-0] [wdi5] call of getControl() failed because of: Error: No DOM element found using the control selector {"id":"__item2-__xmlview0--combobox-0"}
[0-0] [wdi5] error retrieving control: __item2-__xmlview0--combobox-0
```
So the ID assigned to the aggregated item does not match any DOM element in the document. I’ve opened an issue about this at the OpenUI5 repo SAP/openui5#3477, because it doesn’t seem to be a way to get the domRef of the aggregation by means of the UI5 API. 

Hope this info is of any help!

**Comment by vobu** [comment]
thanks for digging deeper @ph-alsvik! 🙌 
and extra props for the excellent bug report for our UI5 friends https://github.com/SAP/openui5/issues/3477 🤙
→ let's see where that UI5 issue leads, then follow up with a fix here

**Comment by vobu** [comment]
just to update you @astarovojtov and @ph-alsvik: after reading through https://github.com/SAP/openui5/issues/3477 and doing some triage, we decided to surface an additional api in `wdi5` to retrieve the `items` aggregation of the ComboBox.
This is to mitigate the shortcoming described in https://github.com/SAP/openui5/issues/3477 w/ the ComboBox holding `sap.ui.core.Item`s but rendering `sap.m.StandardListItem`s. 
Work happens in #121 so as soon as that goes in, this wdi5 "bug" should be resolved.
