### ISSUE TITLE
How to resolve error : [wdi5] bridge was not initialized correctly

### ISSUE THREAD

**Issue by nair-sumesh** [js-soft/wdi5#122]
**Describe the bug**
Receiving below error several times at the beginning of the test code execution.
My test cases passed successfully though.
Could this message be resolved or suppressed.  

**Code**
```JS
      const elem = await $('#meAreaHeaderButton')
      await elem.waitForDisplayed({ timeout: 3000 });

      const _ui5Service = require('wdio-ui5-service').default
      const wdioUI5Service = new _ui5Service()
      wdioUI5Service.injectUI5()
```
After this statement the error is raised several times in a row, before the actual actions/assertions are executed.

**Logs/Console Output**

```shell
[0-0] [wdi5] bridge was not initialized correctly
[0-0] 2022-01-25T12:55:45.974Z ERROR @wdio/utils:shim: Error: [wdi5]bridge was not initialized correctly
[0-0]     at Object.error (C:\Users\MyUser\git\MyUser\wdi5_resmon\node_modules\wdio-ui5-service\src\lib\Logger.js:77:19)
[0-0]     at Object.injectUI5 (C:\Users\MyUser\git\MyUser\wdi5_resmon\node_modules\wdio-ui5-service\src\lib\wdioUi5-index.js:283:16)
[0-0]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[0-0]     at async Service.injectUI5 (C:\Users\MyUser\git\MyUser\wdi5_resmon\node_modules\wdio-ui5-service\src\service.js:62:9)
[0-0]     at async Service.startWDI5 (C:\Users\MyUser\git\MyUser\wdi5_resmon\node_modules\wdio-ui5-service\src\service.js:49:13)
[0-0]     at async Service.before (C:\Users\MyUser\git\MyUser\wdi5_resmon\node_modules\wdio-ui5-service\src\service.js:6:9)
[0-0]     at async Promise.all (index 0)
[0-0]     at async executeHooksWithArgsShim (C:\Users\MyUser\git\MyUser\wdi5_resmon\node_modules\@wdio\utils\build\shim.js:101:20)
[0-0]     at async Runner.run (C:\Users\MyUser\git\MyUser\wdi5_resmon\node_modules\@wdio\runner\build\index.js:99:9)
```

**Runtime Env (please complete the following information):**
- `wdi5/wdio-ui5-service`-version:  0.8.1
- `wdio`-version : 7.16.12
- `node`-version : 14.17.4
 - `OS`: WIN10
 - `Browser + Version` : ChromeDriver 96.0.4664.45

**Comment by vobu** [comment]
if you're late-injecting `wdi5`, with the new async notation, you need to `await` the injection:

`await wdioUI5Service.injectUI5()`

**Comment by nair-sumesh** [comment]
> if you're late-injecting `wdi5`, with the new async notation, you need to `await` the injection:
> 
> `await wdioUI5Service.injectUI5()`

Thanks @vobu for the suggestion. The occurrence of the error have now reduced to one. 
The error is still raised as soon as the test starts.

**Comment by vobu** [comment]
right on, just for reference: we're having a test for this as well at https://github.com/js-soft/wdi5/blob/develop/wdio-ui5-service/test/ui5-late.test.js
i'm taking the liberty to close this

**Comment by cwang1221** [comment]
@nair-sumesh I met the same issue, and finally I found I missed the `skipInjectUI5OnStart: true` config. Example: https://github.com/js-soft/wdi5/blob/develop/wdio-ui5-service/test/wdio-ui5-late.conf.js#L99

**Comment by nair-sumesh** [comment]
@cwang1221 @vobu In my conf file, I have set 
```
skipInjectUI5OnStart: true   
url: 'index.html'
```
and
``` 
baseUrl,
```

Later in my spec, I call
```
await browser.url(sBaseUrl); // sBaseUrl contains the entire URL path to the SAP system

const _ui5Service = require('wdio-ui5-service').default
const wdioUI5Service = new _ui5Service()
await wdioUI5Service.injectUI5()
```


**Observations**
- The Chrome loads with index.html (an empty page) ✔
- Then the web page navigates to the base url  and user login page is displayed ✔
- Then suddenly the page jumps back to index.html ❌


@vobu Your help is appreciated.

**Comment by dominikfeininger** [comment]
@nair-sumesh do you have 
`wdi5: {
  url: "index.html"
  ...
}`

in your config?

**Comment by nair-sumesh** [comment]
> @nair-sumesh do you have `wdi5: { url: "index.html" ... }`
> 
> in your config?

Yes.
```
  wdi5: {
    screenshotPath: path.join('wdio-ui5-service', 'test', 'report', 'screenshots'),
    logLevel: 'verbose', // error | verbose | silent
    platform: 'browser', // electron, browser, android, ios
    url: 'index.html',
    deviceType: 'web',
    waitForUI5Timeout: 15000,
     skipInjectUI5OnStart: true  
  },
```

**Comment by dominikfeininger** [comment]
The flow with ` skipInjectUI5OnStart: true ` works like:
- open baseUrl // non UI5 page // done by wdio
- nav to some other page with UI5
- call `wdioUI5Service.injectUI5()`
- wdi5 uses the `url` property from config to start

So my guess would be to set the `url` property to empty string `""` in case you don't need it.
