### ISSUE TITLE
Unexpected Token '.' Error. This is due to several uses of Optional Chaining which requires Node.js 14

### ISSUE THREAD

**Issue by webbpage** [js-soft/wdi5#123]
**Describe the bug**
Error: couldn't initialise "wdio-ui5-service".  
SyntaxError: Unexpected token '.'  

After hours of debugging I realized that the error was due to the use of Optional Chaining which is unsupported until Node 14 while the readme states "12.x" as a prerequisite. 

Optional Chaining was found in the following files:
service.js
lib/WDI5.js
lib/wdioUi5-index.js

example: "Logger.setLoglevel(wdi5config?.logLevel || 'error')"

**To Reproduce**
Run wdio-ui5-service with Node.js 12 to reproduce

Resources:
https://stackoverflow.com/questions/59574047/how-to-use-optional-chaining-in-node-js-12
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

**Comment by vobu** [comment]
sorry for the confusion, i've updated all `package.json`s to indicate node >= 14
