### ISSUE TITLE
inconsistent behaviour in get$Shorthand (getItems, getContent, etc.)

### ISSUE THREAD

**Issue by BeastiW** [js-soft/wdi5#124]
Very annoying bug if you want to the the first entry as WDI5 object of an aggregation - it isn't possible at the moment.

If I call getContent(0) on a sap.m.Page WDI5 object, I get an array of objects each containing the attribute 'id'. This is the same behavior as getContent(true).
If I call getContent(1) I would get the WDI5 object. Please fix this bug or make an exception in the README.md (or is it documented?)

I previously thought this could be related to webdriver/sync and stuff. I know the value '0' is considered as falsy, but as argument you could easily compare the input type and concrete value.

**Runtime Env (please complete the following information):**
- `wdi5/wdio-ui5-service`- 0.8.1
- `UI5` version: 1.71.41
- `wdio`-version (output of `wdio --version`): 7.16.14
- `node`-version (output of `node --version`): v16.13.2
 - OS: Mac OS X
 - Browser + Version: chrome 97.0.4692.99

**Comment by vobu** [comment]
> Very annoying bug if you want to the the first entry as WDI5 object of an aggregation - it isn't possible at the moment.

sorry, but not true. there's even an entire test suite for aggregations only: https://github.com/js-soft/wdi5/blob/develop/test/ui5-app/webapp/test/e2e/aggregation.test.js

> If I call getContent(0) on a sap.m.Page WDI5 object, I get an array of objects each containing the attribute 'id'. This is the same behavior as getContent(true).

try adding ˋinteraction: rootˋ to the selector. this stems from the UI5 record replay api.


> If I call getContent(1) I would get the WDI5 object. 

actually this makes sense: you get the proxied UI5 control, transferred from browser- to node-scope. On that wdi5-object, you can then run its' api methods. 
ˋawait browser.asControl(list).getItems(1).getTitle()ˋ

**Comment by BeastiW** [comment]
I am not saying that get$Shorthand is **not** working. Just that get$Shorthand(0) should return the **first item as WDI5** object (in CS we are counting from 0) - as opposed to get$Shorthand(true) which returns the id's off the aggregated objects.

I got `interaction: root` in all of the selector objects.

**Comment by vobu** [comment]
i'll whip up a test case with a `sap.m.Page` and see how `wdi5` performs selecting the `content` aggregation.
but just FTR: `get$Shorthand(0)` is supposed to deliver the first element of aggregation `$shorthand`

**Comment by vobu** [comment]
woah, this was a mean one. 
essentially, TIL:
```js
arg = 0
String(arg) && typeof arg === "number" //> true
arg && typeof arg === "number" //> 0
```
i've added a test working a `sap.m.Page`'s `content` aggregation specifically: https://github.com/js-soft/wdi5/pull/125/files#diff-32620e091294e397d0ea64943ec1a91207353210f31bd1134fe0bfd836b5d66fR13

**Comment by BeastiW** [comment]
`args.length === 0` was already handled, so you could just omit String(arg).

But thanks for your quick fix! Very much appreciated!

Cheers.
