### ISSUE TITLE
In Docker , test fails with an error

### ISSUE THREAD

**Issue by nair-sumesh** [js-soft/wdi5#137]
Hi,

When executing the spec locally on my machine , the test executed with 100% success.
However, when the same spec is executed in a Docker container it ends with the below result.
<img width="843" alt="image" src="https://user-images.githubusercontent.com/12034160/153230704-c372674f-4dff-4443-869d-7055c1f77bf1.png">

I am not an expert at docker. However, I believe a test working in one machine should work same way in the Docker.

_Some observations :_
- I execute twice or thrice all every time its the same result 
  - The screenshots taken by timeline-reporter is capturing the failing step however the image is corrupted.
<img width="968" alt="image" src="https://user-images.githubusercontent.com/12034160/153232030-b84014bc-eaec-4c25-9a46-21f3915fbc1a.png">

  -   Other step's screenshot images are well captured.

**Comment by dominikfeininger** [comment]
Hi,

don't forget Chrome headless is not 100% same as Chrome.

Currently I am investigating the setup possibilities of wdi5/ wdio with docker. Maybe you can find some help here: https://github.com/js-soft/wdi5/tree/feature/docker (WIP).

Can you provide your docker setup. In best case a minimal working example?

Thx

**Comment by nair-sumesh** [comment]
I am using https://www.project-piper.io/steps/dockerExecuteOnKubernetes/.
I don't think its a Chrome headless, atleast I did not set it in the conf file.
Also, is it possible to take screenshot with headless chrome.

For recipe, let me know what exactly are you looking for.
I can help you with that.

**Comment by nair-sumesh** [comment]
Also when executed in non Docker Jenkins job or on local PC the test works perfectly.

**Comment by nair-sumesh** [comment]
UPDATE:
For smaller test the test runs in docker successfully.
For longer test the test fails with above mentioned error message.
For longer test the test passes in a non non docker environment.
