### ISSUE TITLE
refactor: $control.firePress() → $control.press

### ISSUE THREAD

**Issue by vobu** [js-soft/wdi5#138]
$control.firePress() is considered bad practice as it may lead to side effects during the event lifecycle.
additionally, the internal control logic for the event is not triggered.
ex: $listItem.firePress() doesn't highlight the item in the list - as opposed to a regular click, which has that effect.
→ provide a $control.press() event
thanks for reporting @siolto!

**Comment by maximnaidenov** [comment]
No need for more API surface in the form of $control.press(), just make the WDIO fluent API works: getWebElement().click()

**Comment by vobu** [comment]
see https://github.com/js-soft/wdi5/discussions/156
