### ISSUE TITLE
How to check if an element does not exist?

### ISSUE THREAD

**Issue by sebage** [js-soft/wdi5#139]
Hi,

with WebdriverIO selectors we can check if a screen element does not exist at all:

`await expect(await $('[id*=progressFilter]')).not.toExist();`

When using the same with WDI5 selectors it doesn't work, as browser.asControl() throws a 'No DOM element found...' exception:

`await expect(await (await browser.asControl(alertUI.master.progressFilter)).getWebElement()).not.toExist();`

As a workaround i currently use a try-catch block around browser.asControl() and then assert against the exception.

Do you know any better way to check this? If not, are there any plans to support it in future?

**Comment by vobu** [comment]
yep, currently no way to detect non-existend UI5 controls with `wdi5`.
Same goes for invisible controls, but it's on the (soon public) roadmap; corresponding issue: #105 and prepped test #107 

i like your approach to try-catch `browser.asControl(nonExistentSelector)` - probably we should provide an API for that specific use case:
control is not present in DOM tree → error "No DOM element found" → return a value plugging into `not.toExist()`
@dominikfeininger @Siolto thoughts?

**Comment by vobu** [comment]
will not drop this, it's part of the roadmap for 1.0.0

**Comment by vobu** [comment]
still planned

**Comment by dominikfeininger** [comment]
In this specific case we could return the value of the webElement/ wdio element (need to be tested waht this then actually is) which then should be compatible with the `.not.toExist()` call.
