### ISSUE TITLE
TypeScript type declaration package for WDI5?

### ISSUE THREAD

**Issue by yurecz** [js-soft/wdi5#153]
1. Trying to use the WDIO+WDI5 combination with typescript in the strict mode.
2. When using the ui5 control selector:
            browser.asControl({
                selector: {
                    id: 'fe::table::VisitList::LineItem',
                    viewName: 'le.lmd.visitlist.detailss1::VisitListList',
                }
            })

Receive the error message: any
Property 'asControl' does not exist on type 'Browser'.

3. Question: Is any type import for the typescript existing as the npm package which could remove this error?

**Comment by vobu** [comment]
hi, 
- full support for FE elements is still brewed up; we're currently researching how to integrate `sap.fe.test`. expect results by end of next week
- npm package with TS definitions is not yet published; it will be `0.9.0-alpha.0`. about to drop beginning of next week. also see #144 
- hth, v.

**Comment by yurecz** [comment]
@vobu : Many thanks for the quick reply and clear explanation! I will close the question.
