### ISSUE TITLE
aggregationLengthEquals matcher

### ISSUE THREAD

**Issue by Siolto** [js-soft/wdi5#157]

**Comment by vobu** [comment]
won't do this in favor of validating aggregations via the respective UI5 control's native methods, including the `get$Shorthand(true)`:
- `expect((await $control.getAggregation("whatever).length).toStrictEqual(7)`
- `expect((await $control.getWhatever().length).toStrictEqual(7)` 
- `expect((await $control.getWhatever(true).length).toStrictEqual(7)`
