### ISSUE TITLE
How to test with different languages in FLP?

### ISSUE THREAD

**Issue by marianfoo** [js-soft/wdi5#166]
**Describe the bug**
I want to test the output of my fields on different languages in FLP.
When is use the language parameter in the `MainDE.js`file, i get this error:
<Details>

```shell
[chrome 99.0.4844.51 mac os x #0-0] javascript error: Cannot read properties of undefined (reading 'waitForUI5Options')
JavaScript stack:
TypeError: Cannot read properties of undefined (reading 'waitForUI5Options')
    at eval (eval at executeAsyncScript (:552:26), <anonymous>:4:65)
    at eval (eval at executeAsyncScript (:552:26), <anonymous>:29:8)
    at eval (eval at executeAsyncScript (:552:26), <anonymous>:30:4)
    at executeAsyncScript (<anonymous>:552:47)
    at apply.selector.id (<anonymous>:567:29)
    at callFunction (<anonymous>:446:22)
    at <anonymous>:460:23
    at <anonymous>:461:3
  (Session info: chrome=99.0.4844.51)
```

</Details>

When i add the parameter in the config file, it works.
Is hat behavior intended?
Otherwise i need different config files for different languages?

**To Reproduce**
Use this branch https://github.com/marianfoo/ui5-dayjs-sample/tree/wdi5-test

See this commit:
https://github.com/marianfoo/ui5-dayjs-sample/commit/ef21945991da69cefa8a8fe2d0c66e5ab469ba0c

It only works when the parameter `?sap-language=de` is in the config file, not in '`MainDE.js`file

**Expected behavior**
Open page with language parameter without error

**Logs/Console Output**
<Details>

```shell
[chrome 99.0.4844.51 mac os x #0-0] javascript error: Cannot read properties of undefined (reading 'waitForUI5Options')
JavaScript stack:
TypeError: Cannot read properties of undefined (reading 'waitForUI5Options')
    at eval (eval at executeAsyncScript (:552:26), <anonymous>:4:65)
    at eval (eval at executeAsyncScript (:552:26), <anonymous>:29:8)
    at eval (eval at executeAsyncScript (:552:26), <anonymous>:30:4)
    at executeAsyncScript (<anonymous>:552:47)
    at apply.selector.id (<anonymous>:567:29)
    at callFunction (<anonymous>:446:22)
    at <anonymous>:460:23
    at <anonymous>:461:3
  (Session info: chrome=99.0.4844.51)
```

</Details>

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: 0.9.0-alpha.0
- `UI5` version: 1.96.0

**Comment by vobu** [comment]
took a peak, con confirm the behavior you describe - never thought of how we could support pure URL-type manipulation of UI5 core properties (such as `sap-ui-language`). Usually there'd be a button triggering a settings switch on the app level - which you'd then simply `await browser.asControl(langSwitcher).press()`.
But an investigation how we could support URL GET param manipulation at runtime (such as `?sap-language=de#route`) is certainly worth while → will put it on the roadmap.
Sorry for not having an immediate fix, but rather the suggestion to go app-level for setttings change (afore mentioned button).

**Comment by marianfoo** [comment]
Thanks for the quick reply.
Yes, I had already thought about that with the button. It is then but a little more real if that can be done with a button. Unfortunately, however, this is  default not provided in the `flpSandbox.html`.
<Details>

```html
<!DOCTYPE HTML>
<html>
<!-- Copyright (c) 2015 SAP AG, All Rights Reserved -->
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{appTitle}}</title>

    <!-- Bootstrap the unified shell in sandbox mode for standalone usage.

         The renderer is specified in the global Unified Shell configuration object "sap-ushell-config".

         The fiori2 renderer will render the shell header allowing, for instance,
         testing of additional application setting buttons.

         The navigation target resolution service is configured in a way that the empty URL hash is
         resolved to our own application.

         This example uses relative path references for the SAPUI5 resources and test-resources;
         it might be necessary to adapt them depending on the target runtime platform.
         The sandbox platform is restricted to development or demo use cases and must NOT be used
         for productive scenarios.
    -->
    <script type="text/javascript">
        window["sap-ushell-config"] = {
            defaultRenderer: "fiori2",
            bootstrapPlugins: {
                "RuntimeAuthoringPlugin": {
                    component: "sap.ushell.plugins.rta",
                    config: {
                        validateAppVersion: false
                    }
                }
            },
            renderers: {
                fiori2: {
                    componentData: {
                        config: {
                            search: "hidden",
                            enableSetLanguage: true
                        }
                    }
                }
            },
            applications: {
                "dexl2bwquerytest4-display": {
                    title: "BW Query Test",
                    description: "A Fiori application.",
                    additionalInformation: "SAPUI5.Component=de.xl2.bwquerytest4",
                    applicationType: "URL",
                    url: "../"
                }
            }
        };
    </script>

    <script src="../test-resources/sap/ushell/bootstrap/sandbox.js" id="sap-ushell-bootstrap"></script>
    <!-- Bootstrap the UI5 core library -->
    <script id="sap-ui-bootstrap"
        src="../resources/sap-ui-core.js"
        data-sap-ui-libs="sap.f,sap.m,sap.suite.ui.generic.template,sap.ui.comp,sap.ui.core,sap.ui.generic.app,sap.ui.table,sap.ushell"
        data-sap-ui-async="true"
        data-sap-ui-preload="async"
        data-sap-ui-theme="sap_fiori_3"
        data-sap-ui-compatVersion="edge"
        data-sap-ui-language="en"
        data-sap-ui-resourceroots='{"de.xl2.bwquerytest4": "../"}'
        data-sap-ui-frameOptions="allow"> // NON-SECURE setting for testing environment
        </script>
        <script src="../utils/locate-reuse-libs.js" data-sap-ui-manifest-uri="../manifest.json">
        </script>
</head>

<!-- UI Content -->

<body class="sapUiBody" id="content">
</body>

</html>

```

</Details>

I can activate it with
```js
renderers: {
    fiori2: {
        componentData: {
            config: {
                enableSetLanguage: true
            }
        }
    }
},
```
but it does not actually change the language.
![image](https://user-images.githubusercontent.com/13335743/157395152-e9a90020-ccf3-4fcf-9380-53f577ba5a44.png)

The language is also hardcoded in `flpSandbox.html`: 
`data-sap-ui-language="en"`

I have found a method for this ([sap.ui.core.Configuration-->setLanguage](https://ui5.sap.com/sdk/#/api/sap.ui.core.Configuration%23methods/setLanguage)). 
I hope if I call this in the Component.js in time, that the language is pulled correctly.
First test changed the language in the App, so might worth a try.
![image](https://user-images.githubusercontent.com/13335743/157396005-30c7beb0-854f-4979-b96b-a2e50bc00064.png)

URL Parameter would still be easier of course.

**Comment by vobu** [comment]
I'll close this off for now as it'll move on the roadmap.
and by "it" I'm referring to "switching UI language by URL param such as `?sap-language=fr`"
