### ISSUE TITLE
Unable to invoke UI5 native methods for SmartFilterBar

### ISSUE THREAD

**Issue by rwnbiad** [js-soft/wdi5#173]
**Describe the bug**
I'm able to find the UI5 control (`sap.ui.comp.smartfilterbar.SmartFilterBar`) control using locator having id (below).
```
const smartFilterBar = await browser.asControl({
      forceSelect: true,
      selector: {
        id: 'smartFilterBar',
        controlType: 'sap.ui.comp.smartfilterbar.SmartFilterBar',
        viewName: viewName,
        interaction: 'root'
      }
    })
```

During runtime, proxy methods for all the methods that would be available on sap.ui.comp.smartfilterbar.SmartFilterBar (ex: `setFilterData`, `getAllFilterItems`) seem to be available on the located control as well.

<img width="644" alt="Screen Shot 2022-03-09 at 12 39 31 AM" src="https://user-images.githubusercontent.com/93357515/157232107-73381c2e-4b29-41fe-905b-3b09faabbc8f.png">

However, while trying to invoke a method on smartfilterbar, the below error comes up.
```
const smartFilterBar = await browser.asControl({
      forceSelect: true,
      selector: {
        id: 'smartFilterBar',
        controlType: 'sap.ui.comp.smartfilterbar.SmartFilterBar',
        viewName: viewName,
        interaction: 'root'
      }
    }).getAllFilterItems()
```

`[wdi5]call of _getControl() failed because of: Error: waitAsync is already running and cannot be called again at this moment`

Just for the sake of completeness, I also tried using `setFilterData` method on SmartFilterBar. 

```
const control = await browser.asControl({
      forceSelect: true,
      selector: {
        id: 'smartFilterBar',
        controlType: 'sap.ui.comp.smartfilterbar.SmartFilterBar',
        viewName: viewName,
        interaction: 'root'
      }
    })
    await control.setFilterData({ productDisplayId: 'D2O_XY00174197' })
```
Again, during debugging the proxy method seems available.
<img width="557" alt="Screen Shot 2022-03-09 at 1 54 34 AM" src="https://user-images.githubusercontent.com/93357515/157242368-140b502b-f6bc-4b65-9022-9bff11235d86.png">

But running the test to completion results in the below error.

`[wdi5]call of setFilterData failed because of: function setFilterData does not exist on control sap.ui.comp.smartfilterbar.SmartFilterBar!`

**To Reproduce**

**Expected behavior**
I thought this is a fairly straight-forward use case. It should return an array for filter items.

**Logs/Console Output**
`[wdi5]call of _getControl() failed because of: Error: waitAsync is already running and cannot be called again at this moment`

**Screenshots**
See above

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: 0.8.2
- `UI5` version: 1.98.0
- `wdio`-version (output of `wdio --version`): @wdio/cli (version: 7.16.16)
- `node`-version (output of `node --version`): v16.14.0
- OS: MacOS Monterey (12.2.1)
- Browser + Version [Chrome: Version 99.0.4844.51 (Official Build) (arm64)]

**Comment by rwnbiad** [comment]
Just for the sake of completeness, I also tried using `setFilterData` method on SmartFilterBar. 

```
const control = await browser.asControl({
      forceSelect: true,
      selector: {
        id: productStructuresSmartFilterBarName,
        controlType: 'sap.ui.comp.smartfilterbar.SmartFilterBar',
        viewName: viewName,
        interaction: 'root'
      }
    })
    await control.setFilterData({ productDisplayId: 'D2O_XY00174197' })
```
Again, during debugging the proxy method seems available.
<img width="557" alt="Screen Shot 2022-03-09 at 1 54 34 AM" src="https://user-images.githubusercontent.com/93357515/157242368-140b502b-f6bc-4b65-9022-9bff11235d86.png">

But running the test to completion results in the below error.
```
[wdi5]call of setFilterData failed because of: function setFilterData does not exist on control sap.ui.comp.smartfilterbar.SmartFilterBar!
```

**Comment by vobu** [comment]
hi, thanks for providing details and context for your issue 👍 
and indeed, this smells 👃 like a bug
could you please upgrade `wdi5` (or more precisely `wdio-ui5-service`) to the latest `0.9.0-alpha.1` and see if your issue still persists? we had a major rewrite happening from `0.8.x` → `0.9.x`.
thanks!

**Comment by rwnbiad** [comment]
@vobu Thanks. The above two native UI5 APIs of SmartFilterBar work fine with 0.9.0-alpha.1
Can we use the release of wdio-ui5-service productively? Or is there some sort of wait time.

I'm closing this issue since, those methods I originally reported work fine. However, there seems to be another issue. I'll create another Github issue for it. Thanks again.

**Comment by vobu** [comment]
> Can we use the release of wdio-ui5-service productively? Or is there some sort of wait time.

`0.9.0-*` is safe to use in the sense that we'll not change APIs or method signatures anymore.
There'll mostly be additions to the overall feature scope.
This week, a first release candidate will drop; the final `0.9.0` release will most likely happen toward the end of the month.
