### ISSUE TITLE
Feature-Request : Custom tags in Logger

### ISSUE THREAD

**Issue by nair-sumesh** [js-soft/wdi5#177]
Hi @vobu  ,

The [Logger](https://js-soft.github.io/wdi5/#/usage?id=logger) adds an advantage to the console logs with its color coding and granularity control.
However, if it could also have the flexibility to use a different tag from ```[wdi5]``` when and where required, will help with better user readability of the log.

Thanks and Regards,
Sumesh Nair

**Comment by vobu** [comment]
argh, my bad - given that it's still a manual step publishing `wdi5` until we release the regular `0.9.0`, i forgot to do build of the most current sources prior to publishing... 🤦‍♂️ 
→ just releases `wdio-ui5-service@0.9.0-rc2`
