### ISSUE TITLE
Does WDI5 support FioriElement Generated App ?

### ISSUE THREAD

**Issue by ZhanJohnny** [js-soft/wdi5#198]
**Describe the bug**
When i try to locate the element generated by FE, it seems it is impossible to get the element.

**To Reproduce**
 My code as below: 

    const oButtonSelector = {
        selector: {
          controlType: 'sap.m.Button',
          id: 'com.sap.project.ui.apps.myapp::sap.suite.ui.generic.template.ListReport.view.ListReport::Books--addEntry',
        }
      };  

    const oCreateButton = await browser.asControl(oButtonSelector);  

    await oCreateButton.firePress();
**Expected behavior**
Should be able to located the create button

**Console log
[0-0] [wdi5] call of getControl() failed because of: Error: waitAsync is already running and cannot be called again at this moment
[0-0] [wdi5] error retrieving control: comsap.ctsm.ui.apps.study::sap.suite.ui.generic.template.ListReport.view.ListReport::Studies--addEntrysap.m.Button

**Screenshots**
if applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/50702068/159860635-1ffebe19-5257-4463-a971-f59e0435a79f.png)

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: [0.9.0-rc2]
- `UI5` version: [1.97.0]
- `wdio`-version (output of `wdio --version`): [7.16.2]
- `node`-version (output of `node --version`): [14.18.1]
- OS: [Window10]
- Browser + Version [chrome 99.0.4844.74]

**Comment by vobu** [comment]
Hi, thanks for providing detailed context info 👍 
Out of the box `wdi5` supports selecting FE-like `id`s, see https://github.com/js-soft/wdi5/blob/3458b34a8256a9407c4109ec1aea146e6a95dd64/examples/ui5-js-app/webapp/test/e2e/basic.test.js#L14

the error message you provided (`waitAsync is already running and cannot be called again at this moment`) hints at a busy UI5/FE app that prevents the `RecordReplay` API (that we're using for communicating with the UI5 core) from kicking in.
Any chance that prior to selecting the button you're not `awaiting` a navigation step or similar?

PS: Generic FE support via the "OData v4 test library" is being worked on in #155

**Comment by vobu** [comment]
> Do you have better idea to wait for UI5 core loading?
this very much depends on your test setup/organization, meaning the logic, oder and sequence of your `describe`s and `it`s.
could you probably share the test code in question?

**Comment by ZhanJohnny** [comment]
Hi Vobu,

  Thanks a lot for your help. I would be grateful if you could share some time to check my test spec.  
  My test spec is in [study.spec.js](https://github.wdf.sap.corp/ctsm/ctsm/blob/chore/uiveri5-to-wdi5/test/wdi5/app/study/study.spec.js).

Best Regards
Johnny

**Comment by vobu** [comment]
> Thanks a lot for your help. I would be grateful if you could share some time to check my test spec. My test spec is in [study.spec.js](https://github.wdf.sap.corp/ctsm/ctsm/blob/chore/uiveri5-to-wdi5/test/wdi5/app/study/study.spec.js).

Unfortunately we have no access to SAP-internal GitHub hosting.
So either you post/publish your test setup here - or we can go into a 1:1 support for your case. Please note that the latter would require you to become [a paid sponsor](https://github.blog/2022-02-02-new-sponsors-only-repositories-custom-amounts-and-more/) of this project, which results in exclusive support for you.

**Comment by ZhanJohnny** [comment]
Hi Vobu,

   Oh, I am not ware the you have no access. sorry for that.  currently, i use browser.pause for testing and it works. 
   I will close this issue and try to fix it later.  Thanks a lot again.
