### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'isDisplayed')

### ISSUE THREAD

**Issue by nair-sumesh** [js-soft/wdi5#210]
**Describe the bug**
Error raised when config  `maxInstances` is greater than 1.
``` 
NOTE: The error does not occur when config  `maxInstances : 1` 
```
``` 
NOTE: The error is inconsistent and does not occur at each run. 
```

**To Reproduce**
_set conf as_
```json
  wdi5: {
    screenshotPath: path.join('wdio-ui5-service', 'test', 'report', 'screenshots'),
    logLevel: 'verbose', // error | verbose | silent
    platform: 'browser', // electron, browser, android, ios
    url: 'www.google.com',
    skipInjectUI5OnStart: true,
    deviceType: 'web',
    waitForUI5Timeout: 15000
  },
```

_code snippet_
1.   await browser.url(theFullURLofTheApp)
2.  The usual login mechanism
3. Inject UI5 
    ```js
    const { default: _ui5Service } = require("wdio-ui5-service")
    const ui5Service = new _ui5Service()
    await ui5Service.injectUI5()
    ```
5. get access to an element
   ```js
    const meArea = await browser.asControl({
      timeout: 60000,
      selector: {
        id: 'meAreaHeaderButton'
      }
    })
   ```

6. Failing at step

   ```js
    expect((await meArea.getWebElement()).isDisplayed()).toBeTruthy()
   ```

**Expected behavior**
The element is available (see below screenshot).
I have also validated this with below code before injecting UI5
```js
    const elem = await $('#meAreaHeaderButton')
    await elem.waitForDisplayed({ timeout: 10000 });
```

**Logs/Console Output**

```shell
[0-1] [wdi5] call of getControl() failed because of: TypeError: Cannot read properties of undefined (reading 'compare')
[0-1] [wdi5] error retrieving control: meAreaHeaderButton
[0-1] TypeError in "ValidatingNavigation.Should Validate the Navigation to app"
TypeError: Cannot read properties of null (reading 'isDisplayed')
```

**Screenshots**
![image](https://user-images.githubusercontent.com/12034160/161086815-1e545b8d-612e-44b7-b0b2-7a905f4214f1.png)

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: 0.9.0-rc3
- `UI5` version: 1.98.0
- `webdriverio`-version (output of `wdio --version`): 7.19.1
- `node`-version (output of `node --version`): v16.13.2
- OS: WIN10
- Browser + Version  - Chrome 100.0.4896.60

**Comment by dominikfeininger** [comment]
Not sure how it is related with the `maxInstances` but just noticed that you missed an await for the `isDisplayed()` call, right?

```
 expect(await (await meArea.getWebElement()).isDisplayed()).toBeTruthy()
```

**Comment by nair-sumesh** [comment]
🫢
