### ISSUE TITLE
Warning 'undefined has no sReplFunctionNames'

### ISSUE THREAD

**Issue by sebage** [js-soft/wdi5#241]
We have disable almost every console output by setting wdio and wdi5 loglevel to 'error' and starting chrome with parameter '--log-level=3'.
After this we see for every browser.asControl call the warning **undefined has no sReplFunctionNames** or **sap.m.CheckBox{"editable":true} has no sReplFunctionNames**. But the tests are working fine.

Is there a way to avoid this warning (besides setting loglevel to silent)?

WDI5 version 0.9.0-rc4.2
SAPUI5 1.101.0
WDIO version 7.19.6
Node version v16.12.0
OS: Windows 10 Enterprise
Chrome 100.0.4896.127 (Official Build) (64-bit)

**Comment by dominikfeininger** [comment]
on it. Will be fixed soon.
