### ISSUE TITLE
Issue with calling getItems() on sap.m.List

### ISSUE THREAD

**Issue by ph-alsvik** [js-soft/wdi5#243]
Hello JS-Soft! 😃 

**Describe the bug**
I am trying to test Fiori apps with list controls, but the test fails when trying to get the items aggregation from a list control by calling ```getItems()```.

**To Reproduce**

I have used [this sample app](https://sapui5.hana.ondemand.com/#/entity/sap.m.List/sample/sap.m.sample.ListCounter) and trying out the following test script on it:

```javascript
describe("Test list sample app", () => {
    it("Verifies that list is not empty", async () => {
        oSelector = {
            forceSelect: false,
            selector: {
                interaction: "root",
                id: "list",
                viewName: "sap.m.sample.ListCounter.List"
            }
        };
        const control = await browser.asControl(oSelector);
        const listItems = await control.getItems();
        await expect(listItems.length).not.toEqual(0);
    });
});
```
As you see all the test does is retrieve the list items and check if the total number of items is not zero.

**Logs/Console Output**

I get the following error message in the console:

```shell
ERROR webdriver: Request failed with status 404 due to invalid session id: invalid session id
```

**Screenshots**

![Screenshot 2022-04-26 at 16 09 10](https://user-images.githubusercontent.com/82877124/165319491-04dc48fc-38a2-43b4-95dc-de8d4a4b5653.png)

![Screenshot 2022-04-26 at 16 09 52](https://user-images.githubusercontent.com/82877124/165319643-b7760292-4327-4c50-af45-b544e037db8d.png)

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: 0.9.0-rc4.2
- `UI5` version: 1.98.0
- `wdio`-version: 7.17.4
- `node`-version: v17.8.0
- OS: MacOS
- Browser + Version: chrome 100.0.4896.127

**Comment by vobu** [comment]
that most certainly is an issue w/ `chromedriver` not running, thus `wdi5`/WebdriverIO shows the connection error to port `9515`. Please make sure you have `npm i chromedriver wdio-chromedriver-service` and added it in the "services" section to `wdio.conf.(j|t)s`. Then `chromedriver` should start automatically once you run `wdi5`/`wdio`.

**Comment by ph-alsvik** [comment]
Yes, I have ChromeDriver service for WDIO installed. I should have been clearer in my description of the issue: 
The test is running. The ChromeDriver session is created. The issue happens when I call getItems() on the WDI5 representation of a sap.m.List control. The test fails before returning all the items in the list.

I’m speculating here, but it seems to me that the ChromeDriver session is ended prematurely. Looking at the output from the test I see this line here:
![Screenshot 2022-04-28 at 16 05 30](https://user-images.githubusercontent.com/82877124/165771060-e0428bb2-9b8d-4e12-b29b-e1dd8dcb4dd6.png)

Which happens before the .getItems() returns. The delete session request shouldn't be sent before the test is finished. As far as I know there is no issue with the test script itself.

**Comment by vobu** [comment]
I just tried replicating it with one of our own tests:
```js
it.only('should allow the deep entry to "Other" view using wdi5 helper class and the UI5 router', async () => {
        const oRouteOptions = {
            sComponentId: "container-Sample",
            sName: "RouteOther"
        }
        await wdi5.goTo("", oRouteOptions)

        const items = await browser.asControl(listSelector).getItems()
        for (const listItem of items) {
            const title = await listItem.getTitle()
            wdi5.getLogger().log(title)
        }
        expect(items.length).toEqual(9)
    })
```
the test runs successfully and
and the log output is as expected:
```
[0-0] [wdi5] Nancy Davolio
[0-0] [wdi5] Andrew Fuller
[0-0] [wdi5] Janet Leverling
[0-0] [wdi5] Margaret Peacock
[0-0] [wdi5] Steven Buchanan
[0-0] [wdi5] Michael Suyama
[0-0] [wdi5] Robert King
[0-0] [wdi5] Laura Callahan
[0-0] [wdi5] Anne Dodsworth
```
how many items does your list contain? eventually a `grow`ing issue there?

**Comment by vobu** [comment]
btw: if you're only asserting the number of items in the list, pass the boolean `true` to `getItems`
→ `const listItems = await control.getItems(true);`
much quicker/better performance

**Comment by ph-alsvik** [comment]
Hi Volker!

The list has around 100 items.  There is no ```growing``` property set on the List control, so all the list items are present in the DOM when the app starts up.

Indeed, in the case of this test it runs much faster when passing ```true``` to ```getItems```, but if you need to do other types of operations on the list items, such as checking if there is an item with a specific text property, how would you do that? Your only option is to get all the ListItems themselves, then check each one, right?

**Comment by Siolto** [comment]
for checking a specific property in an list you can do something like this:

``` javascript
selector: {
    controlType: "sap.m.CustomListItem",
    viewName: "sap.m.sample.ListCounter.List"
    properties: {
        text: "myText"
    },
    ancestor: {
        id: "list"
    }
}
```

This will search for all CustomListItems where the ancestor is the list and has a specific text property.

**Comment by vobu** [comment]
what @Siolto said, or (given you know the index of the item in the list) even simpler doing `await browser.asControl(listSelector).getItems(4)` with `4` being the index

**Comment by ph-alsvik** [comment]
Thank you, @Siolto! This worked for me, but only after adding ```viewName: viewName: "sap.m.sample.ListCounter.List"``` to the ancestor object, so:

```javascript
selector: {
    controlType: "sap.m.CustomListItem",
    viewName: "sap.m.sample.ListCounter.List"
    properties: {
        text: "myText"
    },
    ancestor: {
        id: "list",
       viewName: "sap.m.sample.ListCounter.List"
    }
}
```

**Comment by dominikfeininger** [comment]
solved
