### ISSUE TITLE
browser.asControl is not a function

### ISSUE THREAD

**Issue by malkoto1** [js-soft/wdi5#245]
**Describe the bug**
I am trying to run my first wdi5 hello world test. I have gone through the documentation and have done a basic setup in my application.

**To Reproduce**
I have the following hello world test code:
```
const wdi5 = require('wdi5');

const selectAllCheckBox = {
    selector: {
        controlType: "sap.m.CheckBox",
        id: /All$/
    }
}

describe('My Login application', () => {
    it('should login with valid credentials', async () => {
        await browser.url(`myurl`);
        await browser.asControl(selectAllCheckBox);
    });
});
```

I have tried with and without the require line. 

No matter what I do, I always end up with "browser.asControl" is not a function.

I have watched you video on youtube and the require there is as on the following screenshot:
![image](https://user-images.githubusercontent.com/1436515/165505718-83797603-3e6e-4885-ab2a-0830a35f6714.png)

There is no clear explanation on what shall I do to run my brand new first test that just opens my application.

There is some problem as I cannot just run a normal hello world test. 

Please explain where is the problem.

**Comment by Siolto** [comment]
Hi Radoslav,

thanks for trying out wdi5! 
It could be that something in the `conf.js` file is not configured correctly. Could you also share that file? When the setup ist done correctly and you reference the url to your application in the configuration file you can also skip the `browser.url(...)` part in your test code .

Best regards
Simon

**Comment by malkoto1** [comment]
Hi Simon, 

Thanks for the quick answer. Please see the file attached.
[wdio.conf.js.txt](https://github.com/js-soft/wdi5/files/8571625/wdio.conf.js.txt)

**Comment by malkoto1** [comment]
I've gone through the error once more and am abe to see the following thing:

[0-0] 2022-04-27T11:13:43.498Z WARN @wdio/mocha-framework: Unable to load spec files quite likely because they rely on `browser` object that is not fully initialised.
[0-0] `browser` object has only `capabilities` and some flags like `isMobile`

I hope that this means something meaningful.

**Comment by Siolto** [comment]
Hi Radoslav,

it looks like you are missing the actual [configuration](https://js-soft.github.io/wdi5/#/configuration) part of wdi5 after the installation in the `conf.js`.

```javascript
wdi5: {
    screenshotPath: require("path").join("some", "dir", "for", "screenshots"), // [optional] {string}, default: ""
    screenshotsDisabled: false, // [optional] {boolean}, default: false; if set to true, screenshots won't be taken and not written to file system
    logLevel: "verbose", // [optional] error | verbose | silent, default: "error"
    url: "index.html", // [mandatory] {string} name of your bootstrap html file. If your server autoredirects to a 'domain:port/'-like root url, use empty string ''
    skipInjectUI5OnStart: false, // [optional] {boolean}, default: false; true when UI5 is not on the start page, you need to later call <wdioUI5service>.injectUI5() manually
    waitForUI5Timeout: 15000 // [optional] {number}, default: 15000; maximum waiting time in milliseconds while checking for UI5 availability
  }
```

After you configured wdi5 your desired way, please try it again.

Regards
Simon

**Comment by malkoto1** [comment]
All right! I've added it.

Now I have new error:

[chrome 101.0.4951.41 windows #0-0] javascript error: Cannot read properties of undefined (reading 'waitForUI5Options')
JavaScript stack:
TypeError: Cannot read properties of undefined (reading 'waitForUI5Options')

This is without the "require". If I leave it, it says that wdi5 cannot be found.

**Comment by Siolto** [comment]
Seems like there is still an issue with your setup. Can you please check following things:

- That you automatically start your ui5 application on startup. Otherwise you have to use `skipInjectUI5OnStart: true` and use the [late injection](https://js-soft.github.io/wdi5/#/configuration?id=skipinjectui5onstart) of wdi5

- `package.json`:
  ```json
  "devDependencies": {
      "wdio-ui5-service": "..." // the higher the installed version the better
    },
  ```

- Also your referenced module name in the `require` statement is wrong, it should look like this:
  ```javascript
  const { wdi5 } = require("wdio-ui5-service")
  ```

**Comment by malkoto1** [comment]
Okay, the page loaded.

Now a second question comes up: I have a BusyIndicator and the test does not wait for it. The following error comes up.

_element click intercepted: Element <button id="__xmlview0--showSummaryButton" data-sap-ui="myButton" class="sapMBtnBase sapMBtn sapUiTinyMarginBegin sapMBarChild">...</button> is not clickable at point (407, 62). Other element would receive the click: <div class="sapUiLocalBusyIndicator sapUiLocalBusyIndicatorSizeBig sapUiLocalBusyIndicatorFade sapUiLocalBusyIndicatorFade" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuetext="Busy" alt="" tabindex="0" title="Please wait">...</div>
  (Session info: chrome=101.0.4951.41)_

Is there something to configure for that?

**Comment by Siolto** [comment]
Busy Indicators are always a little bit tricky. A possible solution is probably to use standard `wdio` checks like `isClickable()`. [Here](https://js-soft.github.io/wdi5/#/recipes?id=using-wdio-functions) is an example how you can retrieve the `wdio` object and [here](https://webdriver.io/docs/api/element/isClickable/) is an example how you can wait that an object is clickable
