### ISSUE TITLE
getBindingContext() can not return object

### ISSUE THREAD

**Issue by marianfoo** [js-soft/wdi5#248]
**Describe the bug**
I want to get the binding of a CustomListItem.  
the code i describe here can be found here:
https://github.com/marianfoo/ui5-community.github.io/blob/eca11e69647410c8bceb01eff25c1aa34da84e40/src/test/e2e/search.test.js#L11-L32
I tried it in two ways:
#### getBindingContext
https://github.com/marianfoo/ui5-community.github.io/blob/eca11e69647410c8bceb01eff25c1aa34da84e40/src/test/e2e/search.test.js#L17-L24
i get the list items with:
`const listItems = await list.getAggregation("items");`
then 
`const bindingContext = await listItems[0].getBindingContext("data");`
i get a result similar to in browser
**browser**
![image](https://user-images.githubusercontent.com/13335743/166106695-d26a8b6c-95c7-4934-b962-53841e7eb5f8.png)
**vsc debugger**
![image](https://user-images.githubusercontent.com/13335743/166106700-22417e21-84cc-47c1-8695-4bc067c7de6d.png)

in Browser i can use `getObject()` on the BindingContext to get the object
![image](https://user-images.githubusercontent.com/13335743/166106729-a487cfc8-6d39-4991-8ceb-2febc210b8ba.png)
in wdi5 this does not work
![image](https://user-images.githubusercontent.com/13335743/166106763-ea8fdbef-9a97-4459-a468-ea5ba45b6ef0.png)

#### model Property
https://github.com/marianfoo/ui5-community.github.io/blob/eca11e69647410c8bceb01eff25c1aa34da84e40/src/test/e2e/search.test.js#L27-L31
The other way i tried is with the model and `getProperty()`.
This works in the browser:
![image](https://user-images.githubusercontent.com/13335743/166106819-6cdf9192-8c41-4381-9674-66d4f1b5f5e9.png)

but not in vsc:
![image](https://user-images.githubusercontent.com/13335743/166106829-3709c1df-777a-46b7-966b-2f32ee89c2a8.png)

**To Reproduce**
Test Project on this branch https://github.com/marianfoo/ui5-community.github.io/tree/add-wdi5

1. `git clone https://github.com/marianfoo/ui5-community.github.io`
2. `git checkout add-wdi5`
3. `npm install`
4. `npm start`
5. `npm run wdio`

**Expected behavior**
Access binding in some way

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: 0.9.0-rc4.3
- `UI5` version: 1.101.0
- `wdio`-version (output of `wdio --version`): 7.19.6
- `node`-version (output of `node --version`): v16.13.0
- OS: Windows 10
- Browser + Version: chrome 100.0.0

**Comment by dominikfeininger** [comment]
Hi, nice issue. `npm build` + `npm start` is missing ;) 

Yep, you are right. This needs some more documentation.

Since under the hood (almost) every method on a wdi5 control is executed by https://github.com/js-soft/wdi5/blob/main/client-side-js/executeControlMethod.js the return object of any method like `getBindingContext()` `getBinding` etc. is processed by this line

https://github.com/js-soft/wdi5/blob/fd03800eee4f0f6c0b63e9896ce2888c49d789b0/client-side-js/executeControlMethod.js#L58 
```
result = JSON.parse(
        JSON.stringify(
            window.wdi5.removeCyclic(result),
            window.wdi5.getCircularReplacer()
        )
    )
}
```

wich currently does not allow cyclic objects or functions to be part of the return object. 

This all is caused by the fact that wdio does not allow all return types.

Maybe you can partly get around this by calling properties of the objects instead of methods like `.getBinding('items').oModel` instead of `.getBinding('items').getModel()`.

**Comment by marianfoo** [comment]
Hey Dominik,
thank you for your answer.
You´re right, but `npm start` is enough ;)
Updated the issue description.

Unfortunately, your suggested approach does not work either:
![image](https://user-images.githubusercontent.com/13335743/166153759-712e6958-9d72-41d6-9d57-d86d2464525d.png)

Also there is not data on the model.
i also threw in a `browser.pause(5001)`, but apparently the binding is already complete.
![image](https://user-images.githubusercontent.com/13335743/166153851-5f678cb2-ced7-4cda-a060-73e802bf0367.png)

**Comment by marianfoo** [comment]
I had another idea, but unfortunately it didn't work either.
Here is the commit on the branch:
https://github.com/marianfoo/ui5-community.github.io/commit/25ce74837f7372448af5e968cdfb417c794a4496
This is a custom control that I access and i´d like the property `name`.
So I should be able to access it with "getName()".
But I guess it's the same problem as above.
I suspect it is not the custom control, but with a standard control a similar error would occur.

Works in browser:
![image](https://user-images.githubusercontent.com/13335743/167127314-8f584d00-0e38-470f-b956-3251cecbd322.png)

Does not work in wdi5:
![image](https://user-images.githubusercontent.com/13335743/167127355-1c09a44c-fb58-4738-a61e-b5c867044787.png)

**Comment by marianfoo** [comment]
My workaround is using the web element.
Not really an ideal solution:
https://github.com/marianfoo/ui5-community.github.io/blob/43d426dc01cabcedb68af653d091f704d5f6b1e4/src/test/e2e/search.test.js#L21-L25
![image](https://user-images.githubusercontent.com/13335743/167252417-5f30244c-e224-4ea8-b08e-19c9e23f5bad.png)

**Comment by vobu** [comment]
Hi Marian, two things:
1. you can achieve the same result as in your last screenshot by doing:
```js
const innerText = await browser.asControl(listSelector).getItems(0).getText()
```
Attention: start with `browser.asControl` for fluent async api; starting from a retrieved UI5 element, then using the fluent async api will _not_ work:
```js
const list = await browser.asControl(listSelector)
const innerText = await list.getItems(0).getText() // meeeh, will bail
```

2. we're well aware of the issue of calling methods on a retrieved UI5 object, e.g.
```js
const model = await list.getBinding('items').oModel
const property = await model.getProperty("/path/to/binding/prop")
```
this is an architectural challenge that we're discussing currently. Will get back to you asap we have something planned.

**Comment by marianfoo** [comment]
Hi Volker,

thanks for your comment.
Unfortunately your suggestion does not work. ([`branch`](https://github.com/marianfoo/ui5-community.github.io/tree/wdi5-vobu))

```js
const innerText = await browser.asControl(listSelector).getItems(0).getText()
```

![image](https://user-images.githubusercontent.com/13335743/167787715-07ce1d2f-e45f-47a3-9fcb-df5a4f280c95.png)
![image](https://user-images.githubusercontent.com/13335743/167787777-089bad4f-82af-4268-ba5c-144b2fa95399.png)


This might be a little more complex example because this is a [custom control](https://github.com/ui5-community/bestofui5-website/blob/main/src/control/PackageListItemContent.control.xml) with several texts in the item.
I try to get this from the Item, which is called `name`, so i could access it in the browser with:

```js
this.getView().getParent().byId("AllPackages").getController().byId("listAllPackages").getItems()[0].getAggregation("content")[0].getName()
```
![image](https://user-images.githubusercontent.com/13335743/167790159-ffc74891-4d2a-4b11-9a4d-b748447dd151.png)

**Comment by dominikfeininger** [comment]
Hi @marianfoo thanks for the inspiration we will try to refactor the return types to a more generic type. This refactoring will be tracked here: https://github.com/js-soft/wdi5/issues/252

**Comment by marianfoo** [comment]
Thanks!
If you need my help out input just ping me

**Comment by dominikfeininger** [comment]
will be continued in #252
