### ISSUE TITLE
Cannot select Input Control under wizard by id

### ISSUE THREAD

**Issue by TanviiG** [js-soft/wdi5#264]
**Describe the bug**
In our application, we are using [wizard](https://openui5.hana.ondemand.com/#/entity/sap.m.Wizard) component in our UI. I am unable to select the Input control defined under it by providing id.

The selector which I used is as follows: 

```
const inputSelector = {
        wdio_ui5_key: "inputSelector",
        forceSelect: true,
        timeout:15000,
        selector: {
              id: "iinputControlId",
              controlType:"sap.m.Input"            
        }

    }
    await browser.asControl(inputSelector)
```
**To Reproduce**

**Expected behavior**
Expected to have control of the input control. I could although select the input control by providing binding path. Can you please explain if this is something intentional that we cannot get Input Control only by its ID? Or the problem is that it is defined under wizard component? 

**Logs/Console Output**
if applicable, please copypasta _code-fenced_ log output, e.g.

`[wdi5] call of interactWithControl() failed because of: Error: Could not execute interaction ENTER_TEXT on control {"controlType":"sap.m.Input","id":"wizFirstNameInput","viewName":"sap.ui.demo.addressmgr.view.BupaWizard"}. Error: Error: No controls found using selector {"controlType":"sap.m.Input","id":"wizFirstNameInput","viewName":"sap.ui.demo.addressmgr.view.BupaWizard"}
`

```shell
$> ...
```

**Screenshots**
if applicable, add screenshots to help explain your problem.

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: ^0.9.0-rc4.3
- `UI5` version: 2.14.9
- `wdio`-version (output of `wdio --version`): ^7.19.7
- `node`-version (output of `node --version`): v14.17.0
- OS: [e.g. Linux openSuSE]
- Browser + Version [e.g. chrome 97.0.4692.71]

**Additional context**
Add any other context about the problem here,
e.g. any options the target browser is started with like `--headless` or
if the tests run in a CI environment

**Comment by TanviiG** [comment]
I updated the selector as suggested above but still it did not work. 

selector code: 

```
const firstNameSelector = {
        forceSelect: true, 
        selector: {
            id:"wizFirstNameInput",
            viewName: "sap.ui.demo.addressmgr.view.BupaWizard",
            controlType:"sap.m.Input"
        }
    }
```

 Error:  
`[wdi5] call of interactWithControl() failed because of: Error: Could not execute interaction ENTER_TEXT on control {"controlType":"sap.m.Input","id":"wizFirstNameInput","viewName":"sap.ui.demo.addressmgr.view.BupaWizard"}. Error: Error: No controls found using selector {"controlType":"sap.m.Input","id":"wizFirstNameInput","viewName":"sap.ui.demo.addressmgr.view.BupaWizard"}`

**Comment by Siolto** [comment]
Hi,

is your Wizard opened in a Dialog? If so, you need to add following property to your selector: `searchOpenDialogs: true`. 
If the control is still not found maybe you can open the [Test Recorder](https://sapui5.hana.ondemand.com/#/topic/2535ef9272064cb6bd6b44e5402d531d), select the *raw selector* and have a look what the recorder is generating you.

Regards,
Simon

**Comment by TanviiG** [comment]
Thank you @Siolto &@vobu, by using test Recorder I could get the selector for the control.  In our case it also needed a viewId as a separate parameter or the id string should be concatenated with it. 
Final selector looked something like this: 


```
const firstNameSelector = {
        forceSelect: true, 
        selector: {
            id: "element_id",
            viewId: "viewid",
            controlType:"sap.m.Input"
        }
    }

```
OR

```
const firstNameSelector = {
        forceSelect: true,
        selector: {
            id: "viewid---element_id",
            controlType:"sap.m.Input"
        }
    }
```


Thank you again. I am closing this issue now:).
