### ISSUE TITLE
WDI in piper pipeline

### ISSUE THREAD

**Issue by T1mey** [js-soft/wdi5#270]
I can't find a step in piper pipeline which is for wdi5 testing.
Available one's which might fit are:

npmExecuteEndToEndTests
uiVeri5ExecuteTests

As I need an extra deployment or an extra startup paramter for my apllication the step npmExecuteEndToEndTests doesn't fit.

Not sure if I can use the uiVeri5ExecuteTests for wdi5 tests as well?

Any suggestions or recommendations ?

**Comment by vobu** [comment]
Hi, as we have no control or influence on Project Piper, you might want to contact the SAP colleagues responsible for that project... @hmanchev, can you point @T1mey to the right people please?

**Comment by T1mey** [comment]
> ny suggestions or recommendations ?

I already opened an [issue ](https://github.com/SAP/jenkins-library/issues/3820) in piper repo.
