### ISSUE TITLE
Performance Issues with `getAggregation`

### ISSUE THREAD

**Issue by marianfoo** [js-soft/wdi5#282]
**Describe the bug**
When running `getAggregation` on a `sap.m.List` with more than a few entries, the method takes quit a long time.  

In my example there is a list with 123 entries ([products.json](https://github.com/marianfoo/wdi5-issues-getaggregation/blob/performance-getaggregation/uimodule/webapp/model/products.json)). The total execution time for the test took 47 seconds:

```
[chrome 102.0.5005.115 windows #0-0] Running: chrome (v102.0.5005.115) on windows
[chrome 102.0.5005.115 windows #0-0] Session ID: 71536b0cf2dfff18d49d9d104cadd591
[chrome 102.0.5005.115 windows #0-0]
[chrome 102.0.5005.115 windows #0-0] » \uimodule\webapp\test\search.test.js
[chrome 102.0.5005.115 windows #0-0] ui5 search
[chrome 102.0.5005.115 windows #0-0]    ✓ search should return wdi5 as first result
[chrome 102.0.5005.115 windows #0-0]
[chrome 102.0.5005.115 windows #0-0] 1 passing (47.2s)


Spec Files:      1 passed, 1 total (100% completed) in 00:01:06
```

**To Reproduce**

created with `easy-ui5` and `create-wdi5` 💪

1. `git clone https://github.com/marianfoo/wdi5-issues-getaggregation`
2. `git checkout performance-getaggregation`
3. `npm install`
4. `npm start`
5. `npm run wdi5`

**Expected behavior**
Expected is a faster execution of the method

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: 0.9.3
- `UI5` version: [e.g. 1.98.0]
- `wdio`-version (output of `wdio --version`): 1.96.0
- `node`-version (output of `node --version`): v16.13.0
- OS: Windows 10
- Browser + Version: chrome 102.0.0

**Comment by vobu** [comment]
quick thought before digging deeper: would `$list.getItems(**true**)` work for your use case?
see https://js-soft.github.io/wdi5/#/usage?id=getshorthand-conveniences

**Comment by marianfoo** [comment]
yes, this works a expected:
![image](https://user-images.githubusercontent.com/13335743/174768714-faa6a5ea-13c9-4137-b2d6-08848f669c58.png)

**Comment by vobu** [comment]
cool, then i assume that
```js
const listItems = await list.getItems(true)
const itemText = await browser.asControl({
  selector: {
    id: listItems[0]
    viewName: "..."
  }
}).getText()
expect(itemText).toBe("...")
```
should solve your use case, right?
