### ISSUE TITLE
iOS test fail b/c of bug in appium-webdriveragent

### ISSUE THREAD

**Issue by vobu** [js-soft/wdi5#34]
`appium-webdriveragent 2.26.1` is required by `appium-xcuitest-driver 3.29.0` which is required by `appium 1.18.3`.

but `appium-webdriveragent` < 2.30.1 has a bug when running on case sensitive file systems (such as APFS w/ such a setting):
https://github.com/appium/WebDriverAgent/pull/406/files

so let's hope the next `appium`/`appium-xcuitest-driver` release incorporates the fixed version of `appium-webdriveragent`!

**Comment by dominikfeininger** [comment]
Hi, ist this still open?

**Comment by vobu** [comment]
unfortunately yes
