### ISSUE TITLE
Bug: ui5 service not loaded correctly with version 0.0.3 

### ISSUE THREAD

**Issue by mikezaschka** [js-soft/wdi5#39]
This is in my wdio.conf.js file. I am using wdi5 version 0.0.3.

```javascript
exports.config = {
    // ...
    services: ['ui5'],
    // ...
}
```
On startup wdio throws an error  because it cannot identify _wdio-ui5-service_ as the service behind the keyword _ui5_.

```bash
 ERROR @wdio/utils:initialiseServices: Error: Couldn't find plugin "ui5" service, neither as wdio scoped package "@wdio/ui5-service" nor as community package "wdio-ui5-service". Please make sure you have it installed!
```

I think this is related to some internal refactoring for version 0.0.3 that removed the launcher. According to the documentation (https://webdriver.io/docs/customservices.html), this might still be necessary?!

It works, when I directly include the service class (like you do it in the tests):
```javascript
const ui5Service = require('wdio-ui5-service/src/index')

exports.config = {
    // ...
    services: [
        [ui5Service]
    ],
    // ...
}
```

**Comment by vobu** [comment]
confirmed, our bad.
fix on the way 🤭
