### ISSUE TITLE
Starting WDI5 fails after initial configuration

### ISSUE THREAD

**Issue by tobiashofmann** [js-soft/wdi5#486]
**Describe the bug**
I am going through the installation guide and when running wdi5, I get an error:
SyntaxError: Unexpected token 'export'

**To Reproduce**

1. Create a new ts app project: yo easy-ui5
2. select ts-app. Go throught the wizard
3. run npm start. App opens in browser
4. Add WDI5 as outlined by installation guide. https://ui5-community.github.io/wdi5/#/installation
5. Option: a) quickstart with npm init wdi5
6. Use flavor typescript: npm init wdi5@latest -- --ts
7. This adds a script to package.json: "wdi5": "wdio run ./wdio.conf.ts"
8. Run wdi5: npm run wdi5
9. Error: SyntaxError: Unexpected token 'export'

Additional: the running part of the documentation https://ui5-community.github.io/wdi5/#/running is confusing:
Then, kick off the test(s) via wdio (that, for best practice, should be wrapped in an npm script. Here: npm run test:ui5tooling).

From where does the npm run test:ui5tooling come from? In the package.json part earlier, there are test and wdi5 scripts added.

**Expected behavior**

Going through the installation guide it should be possible to run wdi5 without error. All needed steps to get it working should be included.

**Logs/Console Output**

Installing wdi5

```shell
≡> copying tsconfig.json into "./test"...
≡> copying wdio.conf.ts into "./"
👍 done!
≡> installing wdio + wdi5 and adding them as dev dependencies...
npm WARN deprecated @types/easy-table@1.2.0: This is a stub types definition. easy-table provides its own type definitions, so you do not need this installed.

added 458 packages, removed 14 packages, and audited 1445 packages in 36s

192 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
👍 done!

≡> if your're using eslint, please add the "test"'s tsconfig.json to its' project setting:
    "project": ["./tsconfig.json", "./test/tsconfig.json"]

≡> adding wdi5 start command to package.json...
👍 done!
```

Running: npm run wdi5

```shell
2023-06-15T14:19:53.824Z ERROR @wdio/config:ConfigParser: Failed loading configuration file: /com.myorg.myapp/wdio.conf.ts: Unexpected token 'export'
wdio run <configPath>

Run your WDIO configuration file to initialize your tests. (default)
...
...
...
export const config = {
^^^^^^

SyntaxError: Unexpected token 'export'
    at internalCompileFunction (node:internal/vm:73:18)
    at wrapSafe (node:internal/modules/cjs/loader:1187:20)
    at Module._compile (node:internal/modules/cjs/loader:1231:27)
    at Module.m._compile (/com.myorg.myapp/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
    at Object.require.extensions.<computed> [as .ts] (/com.myorg.myapp/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1125:32)
    at Function.Module._load (node:internal/modules/cjs/loader:965:12)
    at Module.require (node:internal/modules/cjs/loader:1149:19)
    at require (node:internal/modules/helpers:121:18)
```

**Runtime Env (please complete the following information):**

- `wdi5/wdio-ui5-service`-version: latest
- `UI5` version: 1.114.0
- `wdio`-version (output of `wdio --version`): 7.31.1
- `node`-version (output of `node --version`): 20.1.0
- OS: MacOS 13.4
- Browser + Version: chrome

**Comment by vobu** [comment]
`ACK` - the TS app scaffold changed recently and `npm init wdi5 -- --ts` picks up the wrong `tsconfig.json`.
quick fix is to pass `--autoCompileOpts.tsNodeOpts.project` to `wdio`, e.g. in the npm script à la 
`"wdi5": "wdio run ./wdio.conf.ts --autoCompileOpts.tsNodeOpts.project=test/tsconfig.json"`
real fix coming up in `create-wdi5`: https://github.com/ui5-community/create-wdi5
