### ISSUE TITLE
accelerate $sap.m.List.getItems()

### ISSUE THREAD

**Issue by vobu** [js-soft/wdi5#63]
currently `$control.getItems()` returns a `wdi5`-object per list item in the `sap.m.List`'s aggregation.
This doesn't scale for large aggregations.
Resolution ideas
- parameter to `$control.getItems()` on wdi5/node-scope to retrieve item lenght only (e.g. `$control.getItems(bCount)`
- separate count function `$control.getItemsLength()`
- ...

**Comment by dominikfeininger** [comment]
@vobu proposal:

`list.getItems()` to return an array of wdio elements

`list.getItems(true)` to return an array of ui5 controls elements the parameter ist a boolean meaning "deep"

`list.getItems(3)` to return the ui5 control at givven index (3) of the aggregation

**Comment by dominikfeininger** [comment]
https://github.com/js-soft/wdi5/pull/70
