### ISSUE TITLE
Add cli option for save-screenshot=false

### ISSUE THREAD

**Issue by Lea-Zim** [js-soft/wdi5#65]
Running tests that include taking screenshots repeatedly (e.g. during debugging) results in unnecessarily high numbers of screenshots. Commenting out multiple screenshots in various files is a tedious task that might be automated using a cli parameter to skip all screenshot calls.

**Comment by dominikfeininger** [comment]
https://github.com/js-soft/wdi5/pull/69

**Comment by dominikfeininger** [comment]
solved in PR as commented
