### ISSUE TITLE
forceSelect for Aggregations

### ISSUE THREAD

**Issue by Lea-Zim** [js-soft/wdi5#71]
The parameter forceSelect: true can be used to update the internally stored references; however, if the retrieved control is used to call aggregations (e.g. ListControl.getItems(), dialogContro.getButtons()), the resulting reference is always reused. forceSelect: true could be propagated to the aggregated controls to avoid errors due to an outdated reference.

**Comment by vobu** [comment]
> Edit2: of course we also got a workaround - cleanup of the internal WDI5 control cache:
> ` Object.keys(browser._controls).forEach(sKey => { if (browser._controls[sKey]._context) { delete browser._controls[sKey]; } });`

thanks for digging into this!
now that you (and @Lea-Zim 😄 ) have identified the issue, would you come fwd and PR this?!? now that would be rad ;)
